"""initial operational schema

Revision ID: f19386697e34
Revises: 
Create Date: 2026-08-22 21:25:22.774230

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'f19386697e34'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communities',
    sa.Column('region_code', sa.String(length=10), nullable=False),
    sa.Column('region_name', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('name_en', sa.String(length=128), nullable=True),
    sa.Column('emd_name', sa.String(length=64), nullable=True),
    sa.Column('residents', sa.Integer(), nullable=False),
    sa.Column('households', sa.Integer(), nullable=True),
    sa.Column('assisted_mobility_estimate', sa.Integer(), nullable=True),
    sa.Column('vulnerability_note', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('map_x', sa.Float(), nullable=True),
    sa.Column('map_y', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_mode', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_communities'))
    )
    op.create_index('ix_communities_region_code', 'communities', ['region_code'], unique=False)
    op.create_table('incidents',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('region_code', sa.String(length=10), nullable=False),
    sa.Column('region_name', sa.String(length=64), nullable=False),
    sa.Column('hazard', sa.String(length=32), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('declared_by', sa.String(length=64), nullable=False),
    sa.Column('declared_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.String(length=64), nullable=True),
    sa.Column('opening_evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents')),
    sa.UniqueConstraint('code', name=op.f('uq_incidents_code'))
    )
    op.create_index('ix_incidents_region_code', 'incidents', ['region_code'], unique=False)
    op.create_index('ix_incidents_status', 'incidents', ['status'], unique=False)
    op.create_table('shelters',
    sa.Column('region_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('capacity_basis', sa.String(length=64), nullable=True),
    sa.Column('hazards', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('facility_type', sa.String(length=64), nullable=True),
    sa.Column('manager', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('source_dataset_id', sa.String(length=32), nullable=True),
    sa.Column('source_attribution', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_mode', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shelters'))
    )
    op.create_index('ix_shelters_region_code', 'shelters', ['region_code'], unique=False)
    op.create_table('audit_events',
    sa.Column('incident_id', sa.Uuid(), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_audit_events_incident_id_incidents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index('ix_audit_events_incident_id_created_at', 'audit_events', ['incident_id', 'created_at'], unique=False)
    op.create_table('evacuation_plans',
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_by', sa.Uuid(), nullable=True),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_evacuation_plans_incident_id_incidents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evacuation_plans')),
    sa.UniqueConstraint('incident_id', 'version', name='uq_plan_incident_version')
    )
    op.create_index('ix_evacuation_plans_incident_id', 'evacuation_plans', ['incident_id'], unique=False)
    op.create_table('field_tasks',
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('community_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('assignee', sa.String(length=64), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], name=op.f('fk_field_tasks_community_id_communities')),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_field_tasks_incident_id_incidents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_field_tasks'))
    )
    op.create_index('ix_field_tasks_incident_id_status', 'field_tasks', ['incident_id', 'status'], unique=False)
    op.create_table('prediction_runs',
    sa.Column('incident_id', sa.Uuid(), nullable=True),
    sa.Column('recipe', sa.String(length=48), nullable=False),
    sa.Column('region_code', sa.String(length=10), nullable=False),
    sa.Column('hazard', sa.String(length=32), nullable=True),
    sa.Column('horizon_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('model_name', sa.String(length=96), nullable=True),
    sa.Column('model_version', sa.String(length=32), nullable=True),
    sa.Column('served_by', sa.String(length=32), nullable=True),
    sa.Column('feature_mode', sa.String(length=16), nullable=True),
    sa.Column('is_stub', sa.Boolean(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('request_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_prediction_runs_incident_id_incidents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prediction_runs'))
    )
    op.create_index('ix_prediction_runs_recipe_region', 'prediction_runs', ['recipe', 'region_code'], unique=False)
    op.create_index('ix_prediction_runs_requested_at', 'prediction_runs', ['requested_at'], unique=False)
    op.create_table('contact_attempts',
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=True),
    sa.Column('community_id', sa.Uuid(), nullable=False),
    sa.Column('households', sa.Integer(), nullable=False),
    sa.Column('households_confirmed', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=24), nullable=False),
    sa.Column('response', sa.String(length=24), nullable=False),
    sa.Column('follow_up', sa.Text(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_by', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_mode', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], name=op.f('fk_contact_attempts_community_id_communities')),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_contact_attempts_incident_id_incidents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['evacuation_plans.id'], name=op.f('fk_contact_attempts_plan_id_evacuation_plans'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_attempts'))
    )
    op.create_index('ix_contact_attempts_incident_id', 'contact_attempts', ['incident_id'], unique=False)
    op.create_index('ix_contact_attempts_response', 'contact_attempts', ['response'], unique=False)
    op.create_table('field_reports',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('observation', sa.String(length=32), nullable=False),
    sa.Column('access_constraints', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('households_verified', sa.Integer(), nullable=True),
    sa.Column('submitted_by', sa.String(length=64), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('triggered_replan', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_field_reports_incident_id_incidents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['field_tasks.id'], name=op.f('fk_field_reports_task_id_field_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_field_reports'))
    )
    op.create_index('ix_field_reports_incident_id', 'field_reports', ['incident_id'], unique=False)
    op.create_table('plan_items',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Uuid(), nullable=False),
    sa.Column('shelter_id', sa.Uuid(), nullable=True),
    sa.Column('residents', sa.Integer(), nullable=False),
    sa.Column('transport', sa.String(length=160), nullable=True),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], name=op.f('fk_plan_items_community_id_communities')),
    sa.ForeignKeyConstraint(['plan_id'], ['evacuation_plans.id'], name=op.f('fk_plan_items_plan_id_evacuation_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shelter_id'], ['shelters.id'], name=op.f('fk_plan_items_shelter_id_shelters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_items'))
    )
    op.create_index('ix_plan_items_plan_id', 'plan_items', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_plan_items_plan_id', table_name='plan_items')
    op.drop_table('plan_items')
    op.drop_index('ix_field_reports_incident_id', table_name='field_reports')
    op.drop_table('field_reports')
    op.drop_index('ix_contact_attempts_response', table_name='contact_attempts')
    op.drop_index('ix_contact_attempts_incident_id', table_name='contact_attempts')
    op.drop_table('contact_attempts')
    op.drop_index('ix_prediction_runs_requested_at', table_name='prediction_runs')
    op.drop_index('ix_prediction_runs_recipe_region', table_name='prediction_runs')
    op.drop_table('prediction_runs')
    op.drop_index('ix_field_tasks_incident_id_status', table_name='field_tasks')
    op.drop_table('field_tasks')
    op.drop_index('ix_evacuation_plans_incident_id', table_name='evacuation_plans')
    op.drop_table('evacuation_plans')
    op.drop_index('ix_audit_events_incident_id_created_at', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_shelters_region_code', table_name='shelters')
    op.drop_table('shelters')
    op.drop_index('ix_incidents_status', table_name='incidents')
    op.drop_index('ix_incidents_region_code', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index('ix_communities_region_code', table_name='communities')
    op.drop_table('communities')
    # ### end Alembic commands ###
